version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_bank
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: bank_api
    ports:
      - '8000:8000'
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  mongo_data:
